{{- if and .Values.apiKey.value (not .Values.apiKey.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devopsmate-agent.apiKeySecretName" . }}
  namespace: {{ include "devopsmate-agent.namespace" . }}
  labels:
    {{- include "devopsmate-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.apiKey.value | quote }}
{{- end }}
