{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devopsmate-agent.serviceAccountName" . }}
  namespace: {{ include "devopsmate-agent.namespace" . }}
  labels:
    {{- include "devopsmate-agent.labels" . | nindent 4 }}
{{- end }}
