{{- if and .Values.uninstaller.enabled .Values.api.endpoint .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devopsmate-agent.fullname" . }}-uninstaller
  namespace: {{ include "devopsmate-agent.namespace" . }}
  labels:
    {{- include "devopsmate-agent.labels" . | nindent 4 }}
    component: uninstaller
{{- end }}
